apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitor-stack-marvel
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/patelnikhilkumar/telemetry-customer-apps.git
    path: app-monitoring/marvel/manifests/kube-prometheus-stack
    targetRevision: 3.12.2
    plugin:
      name: helm
      env:
        - name: HELM_REPO
          value: https://prometheus-community.github.io/helm-charts
        - name: HELM_CHART
          value: kube-prometheus-stack
        - name: CHART_VERSION
          value: 48.3.4
  destination:
    server: https://kubernetes.default.svc
    namespace: marvel
  project: marvel