apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
spec:
  source:
    repoURL: https://www.cip.audi.de/bitbucket/scm/coc/cocos-gitops.git
    path: manifests/kube-prometheus-stack
    targetRevision: {{ .Values.spec.source.targetRevision }}
    plugin:
      name: helm
      env:
        - name: HELM_REPO
          value: https://prometheus-community.github.io/helm-charts
        - name: HELM_CHART
          value: kube-prometheus-stack
        - name: CHART_VERSION
          value: 18.0.3
  destination:
    server: https://kubernetes.default.svc
    namespace: cocos-infra
  project: cocos-infra