apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./upstream/manifest.yaml
- https://raw.githubusercontent.com/prometheus-community/helm-charts/kube-prometheus-stack-18.0.3/charts/kube-prometheus-stack/crds/crd-alertmanagerconfigs.yaml
- https://raw.githubusercontent.com/prometheus-community/helm-charts/kube-prometheus-stack-18.0.3/charts/kube-prometheus-stack/crds/crd-alertmanagers.yaml
- https://raw.githubusercontent.com/prometheus-community/helm-charts/kube-prometheus-stack-18.0.3/charts/kube-prometheus-stack/crds/crd-podmonitors.yaml
- https://raw.githubusercontent.com/prometheus-community/helm-charts/kube-prometheus-stack-18.0.3/charts/kube-prometheus-stack/crds/crd-probes.yaml
- https://raw.githubusercontent.com/prometheus-community/helm-charts/kube-prometheus-stack-18.0.3/charts/kube-prometheus-stack/crds/crd-prometheuses.yaml
- https://raw.githubusercontent.com/prometheus-community/helm-charts/kube-prometheus-stack-18.0.3/charts/kube-prometheus-stack/crds/crd-prometheusrules.yaml
- https://raw.githubusercontent.com/prometheus-community/helm-charts/kube-prometheus-stack-18.0.3/charts/kube-prometheus-stack/crds/crd-servicemonitors.yaml
- https://raw.githubusercontent.com/prometheus-community/helm-charts/kube-prometheus-stack-18.0.3/charts/kube-prometheus-stack/crds/crd-thanosrulers.yaml

configMapGenerator:
  - name: grafana-dashboards
    namespace: cocos-infra
    files:
    - ./resources/cluster-autoscaler.json
    - ./resources/dpu-mbv.json
    - ./resources/jenkins.json
    - ./resources/spot-instance.json
    options:
      labels:
        grafana_dashboard: "1"